### ISSUE TITLE
Is "recving" an assumed statement?

### ISSUE THREAD

**Issue by do-su-0805** [kazeburo/mackerel-plugin-postfix-log#5]
https://github.com/kazeburo/mackerel-plugin-postfix-log/blob/master/postfixlog/postfixlog.go#L95

I found the `receivingDelay` value displayed as `recving`.
Since ancient times, recv has existed in system calls, etc. Is this statement intended?

I'm thinking of issuing a pull-request if this happens by chance instead of what was expected. ( However, it is a breaking change as it changes the name of the displayed metric )

https://github.com/do-su-0805/mackerel-plugin-postfix-log/tree/fix/recving_to_receiving

**Comment by kazeburo** [comment]
Nice catch.
But I don't want to break metrics.

**Comment by do-su-0805** [comment]
I also don't want to break the metric.
I think we have the option to leave a comment to prevent confusion, or do nothing.
