### ISSUE TITLE
The value of `transmission_delay` is incorrect and is equal to `connection_delay`.

### ISSUE THREAD

**Issue by do-su-0805** [kazeburo/mackerel-plugin-postfix-log#6]
https://github.com/kazeburo/mackerel-plugin-postfix-log/blob/760b6d4a659b58ea3c87c1e4a47d69f075d821c0/postfixlog/postfixlog.go#L98

I think this line should really be `sb.DisplayDelay(now, "transmission", sb. transmissionDelay)`. Correct?

If it is correct, I will issue a Pull-Request.

**Comment by kazeburo** [comment]
It's looks incorrect.
Please Pull-Request.

**Comment by do-su-0805** [comment]
https://github.com/kazeburo/mackerel-plugin-postfix-log/pull/7
I created a pull request. Please check.
